[project]
name = "_awsDc"  # Required
version = "0.0.1"  # Required
requires-python = ">=3.10"
license = {file = "LICENSE.txt"}
dependencies = [ # Optional
  "boto3"
]
[tool.setuptools]
[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"